formatter: markdown table
output:
  file: README.md
  mode: inject
sections:
  show:
    - requirements
    - providers
    - inputs
    - outputs
content: |-
  ```hcl
  {{ include "examples/complete/main.tf" }}
  ```
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}
