---
name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2

      - name: Run Terraform fmt
        run: terraform fmt -check -recursive

      - name: Run Terraform init
        run: terraform init -backend=false

      - name: Run Terraform validate
        run: terraform validate

      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.57.0

      - name: Run TFLint
        run: tflint --init && tflint
